### ISSUE TITLE
Version 1.0.1 for Scala 2.11 is not published to maven repository

### ISSUE THREAD

**Issue by dodnert** [kovacshuni/koauth#1]
The README.md file says to use koauth library version 1.0.1. But that version is not currently available in the sonatype.org repository. I only see version 1.0.0 there.

**Comment by kovacshuni** [comment]
1.0.1 is not released yet. Yes, the README on master is referring to a stable 1.0.1, but the whole master branch is a snapshot. = WIP
Always track the [releases from GitHub](https://github.com/kovacshuni/koauth/releases) and Maven Central. Pre-built nightly/snapshot versions are not available at Maven Central, the master branch is work-in-progress, don't rely on every detail in its readme.

I'll consider, for the future, publishing snapshots and having the readme in a more correct state.
Going to close this with no chage.

**Comment by dodnert** [comment]
In my opinion, it would be helpful if the README file included the information that you wrote in that response. Thank you.

**Comment by kovacshuni** [comment]
+1

**Comment by kovacshuni** [comment]
https://github.com/kovacshuni/koauth/commit/b12dfbd54a8ad0ff14c5a5d64358820dafee2736
