### ISSUE TITLE
Specs2 2.3 causes problems with scalaz

### ISSUE THREAD

**Issue by harshith-c** [kovacshuni/koauth#10]
Can you please upgrade the version of specs2 used in this repository. The old version causes problems when used in conjunction with scalaz as described here: https://github.com/etorreborre/specs2/issues/444

**Comment by kovacshuni** [comment]
I tried to give it a few minutes, but i'm having problem with the `.await` methods, also with common mocks so, i think this needs to be done some other time. If you have time, your help is welcome.

**Comment by harshith-c** [comment]
Please review the above PR and release if it looks good.
