### ISSUE TITLE
Maven repository not working?

### ISSUE THREAD

**Issue by pkasarski** [kovacshuni/koauth#14]
I tried adding the artifact as described in the readme. It couldn't find it, and then when I checked the Sonatype Nexus, the latest version is 1.1.0: https://oss.sonatype.org/#nexus-search;quick~koauth

Is there a new repository?

**Comment by kovacshuni** [comment]
You're right, i can't find it. Interesting because i released just a month ago. I'll take a look.

**Comment by kovacshuni** [comment]
Re-released. Now it's there in my searches. search.maven.org still hasn't catched up yet, but it's a matter of hours, i think. Will check tomorrow. Please see if you can download.
