### ISSUE TITLE
Should document dependency on Java 8 runtime

### ISSUE THREAD

**Issue by dodnert** [kovacshuni/koauth#2]
The com.hunorkovacs.koauth.service.Arithmetic package depends on Java library classes that do not exist in Java 7 or earlier (e.g. java.util.Base64). It would be nice if your README file pointed out this dependency.

**Comment by kovacshuni** [comment]
I just came across this issue also these days, i think i'll revert back to Java 7, i'll try to base64 some other way. Thanks for raising this, still.

**Comment by kovacshuni** [comment]
Compiles with Java 7.
https://github.com/kovacshuni/koauth/commit/9b75da202aadde14df1b0cd3df93c8ae3bfd9e9b
