### ISSUE TITLE
Signature validation issue

### ISSUE THREAD

**Issue by fkrauthan** [kovacshuni/koauth#4]
In file [koauth/service/provider/Verifier.scala line 150](https://github.com/kovacshuni/koauth/blob/master/src/main/scala/com/hunorkovacs/koauth/service/provider/Verifier.scala#L150) you get the diff between the required fields and the provided fields. The problem is that the oauth standard allows to have more then the required fields in the OAuth Authorization header. But you never look into the diff result and always assume the validation failed.

This is a major issue if people are sending more then the required fields in there oauth  Authorization header.

**Comment by fkrauthan** [comment]
OAuth Standard: http://tools.ietf.org/html/rfc5849

> Removed the restrictions from defining additional "oauth_" parameters.
> - Appendix A.  Differences from the Community Edition

**Comment by kovacshuni** [comment]
Also please verify my simplification:
https://github.com/kovacshuni/koauth/commit/98a2084d85adba9bdcdee7995cea2c714411f3e7
Thank you for the contribution.
