### ISSUE TITLE
Non Future implementation of ConsumerService

### ISSUE THREAD

**Issue by BusyByte** [kovacshuni/koauth#9]
I don't really have to await on a future.
Can you create a version of the ConsumerService which doesn't return futures?

**Comment by kovacshuni** [comment]
https://github.com/kovacshuni/koauth-sync

**Comment by kovacshuni** [comment]
Does that help?

**Comment by BusyByte** [comment]
Thanks for creating this, it did simplify my usage.
However it was not quite what I had in mind as now it does this internally:
```scala
Await.result(asyncConsumer.createRequestTokenRequest(request, consumerKey, consumerSecret, callback), 2 seconds)
```
- It is no longer referentially transparent as it can throw an exception
- There is no control over the timeout

What should be done instead is move the content of the futures to an `object`:
```scala
 val paramsList = createBasicParamList().::((ConsumerKeyName, consumerKey))
        .::((ConsumerSecretName, consumerSecret))
        .::((CallbackName, callback))
      KoauthRequest(request, paramsList)
```

```scala
val consumerSecret = request.oauthParamsMap.applyOrElse(ConsumerSecretName, (s: String) => "")
      val tokenSecret = request.oauthParamsMap.applyOrElse(TokenSecretName, (s: String) => "")
      val base = createSignatureBase(request)
      val signature = sign(base, consumerSecret, tokenSecret)
      val list = request.oauthParamsList
        .filterNot(param => ConsumerSecretName == param._1 || TokenSecretName == param._1)
        .::((SignatureName, signature))
      val header = createAuthorizationHeader(list)
      RequestWithInfo(request, base, header)
```
Then you can just refer to the plain `object` functions inside the of the Sync or Async version

The other thing you could possibly do is have the async version delegate to they sync version and just wrap the sync call in a future.

**Comment by BusyByte** [comment]
@kovacshuni ^^

**Comment by kovacshuni** [comment]
I thought about sync and async versions. That's all i have for now, i'm sorry.
I don't have the resources to write both libraries. I could have written the whole thing without Futures, just simply calling everything directly. But finally, i aimed more for the async one and just created this wrapper-style sync. Maintaining two kinds of libraries with the same features but one should use future and one shouldn't is an immense effort.

I could have parametrized the wait time in the sync one.
Try find your use from the existing repos :)

**Comment by kovacshuni** [comment]
feel free to contribute

**Comment by BusyByte** [comment]
@kovacshuni I will PR your original repo and just add two different packages if that sounds ok to you.
I'll try not to disrupt any of the current async functionality.
